### PR TITLE
Updates to version 2.x

### PR DESCRIPTION
**Pull request by SteinerOk**
General purpose to this PR: update to AndroidX for resolving this AGP warning:
```
Your project has set `android.useAndroidX=true`, but configuration `gmsDebugRuntimeClasspath` still contains legacy support libraries, which may cause runtime issues.
This behavior will not be allowed in Android Gradle plugin 8.0.
Please use only AndroidX dependencies or set `android.enableJetifier=true` in the `gradle.properties` file to migrate your project to AndroidX (see https://developer.android.com/jetpack/androidx/migrate for more info).
The following legacy support libraries are detected:
gmsDebugRuntimeClasspath -> com.hwangjr.rxbus:rxbus:2.0.2 -> com.android.support:support-annotations:28.0.0

```

### CODE REVIEW

**Comment by SteinerOk** [comment]
@hwangjr is it possible to release version 2.0.3?🙄

**Comment by hwangjr** [comment]
yep, I will release 2.0.3 as soon as possible.

**Comment by SteinerOk** [comment]
@hwangjr thanks so much, I will waiting🙂

**Comment by hwangjr** [comment]
Already release, pls wait for maven to sync.

**Pull request merged**
